"""Terms / Privacy / Refunds pages, rendered inside the Streamlit app.

Served via the `?page=terms|privacy|refunds` query param so they have real,
linkable URLs (e.g. https://wcpicks26.app/?page=terms) that Stripe Checkout
and the footer can point at.

The trader's legal name + contact email are read from environment variables
so the operator's personal details never live in the public GitHub repo:

    LEGAL_BUSINESS_NAME   e.g. "Jane Smith (sole trader), trading as WC26 Picks"
    LEGAL_SUPPORT_EMAIL   e.g. "support@wcpicks26.app"
    LEGAL_LAST_UPDATED    e.g. "29 May 2026"   (optional)

If they're unset, clearly-marked placeholders are shown so it's obvious the
page still needs the operator's details filled in before launch.
"""
from __future__ import annotations

import os
from datetime import date


def _cfg(key: str, default: str) -> str:
    val = os.environ.get(key)
    if val:
        return val
    try:
        import streamlit as st
        return st.secrets.get(key, default)
    except Exception:
        return default


def _business_name() -> str:
    return _cfg("LEGAL_BUSINESS_NAME", "[OPERATOR LEGAL NAME, set LEGAL_BUSINESS_NAME]")


def _support_email() -> str:
    return _cfg("LEGAL_SUPPORT_EMAIL", "support@wcpicks26.app")


def _last_updated() -> str:
    return _cfg("LEGAL_LAST_UPDATED", date.today().strftime("%d %B %Y"))


def _terms_md() -> str:
    return f"""
# Terms of Service: WC26 Picks
_Last updated: {_last_updated()}_

## 1. Who we are
This service is operated by **{_business_name()}**, United Kingdom, trading as
"WC26 Picks". Contact: {_support_email()}

## 2. What we sell
A one-time digital unlock to a statistical forecasting tool for the 2026 FIFA
World Cup. The tool produces algorithmic predictions of match outcomes and
scorelines for use in prediction contests (e.g. office pools). **We do not
provide betting advice, financial advice, or tipster services, and this is not
a gambling product.**

## 3. Price and payment
£7.00 GBP, one-time payment, processed by Stripe. Your unlock link is delivered
by email, normally within a minute of payment.

## 4. Your right to cancel
Under the Consumer Contracts Regulations 2013 you normally have 14 days to
cancel digital content. By ticking the consent box at checkout and accessing
the unlocked content immediately, you agree the service is supplied at once and
you waive that 14-day cancellation right for content already delivered. Our
refund policy below is more generous.

## 5. Refunds
See our [Refund Policy](?page=refunds). In short: full refund for any reason
before the tournament kicks off on **11 June 2026**; after that, refunds for
genuine technical faults (e.g. you never received your unlock link, or the
service was unavailable).

## 6. What the product does and doesn't do
Predictions are generated by statistical models trained on historical match
data. The model and its measured accuracy (Ranked Probability Score ~0.173 on
internationals) are published openly at our
[GitHub repository](https://github.com/jdgoated1/football-predictor). On our
test data this is statistically indistinguishable from bookmaker odds, i.e.
**comparable to the market, not better than it.** We make no warranty that any
prediction will be correct or that using the tool will help you win any
contest. The service is provided "as is". It does not account for injuries,
suspensions, or team-news after the model's last daily update.

## 7. Your access
Your unlock is tied to a cryptographic token delivered to your email. Please
don't share your unlock link publicly. We may revoke access for misuse (e.g.
mass-sharing or automated scraping).

## 8. Acceptable use
You may not resell the service, scrape its predictions for commercial use,
reverse-engineer the unlock mechanism, or use it to break any law that applies
to you.

## 9. Our liability
Our total liability to you is limited to the amount you paid (£7). We are not
liable for indirect or consequential losses, including any loss in a prediction
contest. Nothing here limits liability that cannot be limited by law (such as
for fraud).

## 10. Changes
We may update these terms; the "last updated" date reflects any change.

## 11. Governing law
These terms are governed by the laws of England and Wales, and disputes fall to
the courts of England and Wales.

---
Questions? Email {_support_email()}.
"""


def _privacy_md() -> str:
    return f"""
# Privacy Policy: WC26 Picks
_Last updated: {_last_updated()}_

**Who controls your data:** {_business_name()}, United Kingdom.
Contact: {_support_email()}

## 1. What we collect
- **Your email address**, collected by Stripe at checkout and used to send you
  your unlock link.
- **Payment details**, handled entirely by Stripe. We never see or store your
  card number.
- **Optional sign-up email.** If you tick the box to get free picks and a
  kickoff reminder, we use your email only to send those messages. It's
  consent-based and you can opt out any time by emailing us.

We do **not** run our own customer database. We don't store your email on our
own servers, it passes through our email-sending step (Resend) only long
enough to deliver your unlock link, and your unlock token itself contains no
personal information.

## 2. Why we collect it
To take your payment (Stripe) and to deliver the product you bought (the unlock
email). That's it.

## 3. Lawful basis (UK GDPR)
Performance of our contract with you (Article 6(1)(b)), we need your email to
deliver what you paid for. For the optional free-picks sign-up, the basis is
your consent (Article 6(1)(a)), which you can withdraw at any time.

## 4. Who processes it for us
- **Stripe**, payment processing. Stripe is the controller of your payment
  data under its own privacy policy. (USA / EU)
- **Resend**, sends your unlock email on our behalf. (EU)
- **Cloudflare**, routes our email and serves the site. (global)

We never sell or rent your data.

## 5. How long it's kept
Stripe retains transaction records as required by law (UK tax law requires
business records for 6 years). Our email-sending logs are minimal and
short-lived.

## 6. Your rights
You can ask us to access, correct, or delete your personal data, or object to
processing. Email {_support_email()} and we'll respond within 30 days. You can
also complain to the UK Information Commissioner's Office (ico.org.uk).

## 7. Cookies
We use only the strictly-necessary cookies Stripe and our hosting require to
make checkout and the app work. We don't use advertising or cross-site tracking
cookies.

## 8. Changes
We'll update this policy as needed; the "last updated" date reflects any change.

---
Questions about your data? Email {_support_email()}.
"""


def _refunds_md() -> str:
    return f"""
# Refund Policy: WC26 Picks
_Last updated: {_last_updated()}_

We want you to feel safe buying.

- **Before kickoff (11 June 2026):** full refund, no questions asked. Just email
  {_support_email()} from the address you bought with.
- **After kickoff:** because the predictions are delivered up front, we don't
  refund for dissatisfaction with how the predictions turn out. We **will**
  refund genuine technical problems, e.g. you never received your unlock link,
  the link didn't work, or the service was down.

Refunds are issued to your original payment method via Stripe. Card refunds can
take 5–10 business days to appear, depending on your bank.

To request a refund, email **{_support_email()}** with the email address you
used at checkout. We aim to respond within 24 hours during the tournament.

---
This does not affect your statutory rights under UK consumer law.
"""


_PAGES = {
    "terms": _terms_md,
    "privacy": _privacy_md,
    "refunds": _refunds_md,
}


def render_legal_page(page: str) -> bool:
    """If `page` is a known legal page, render it and return True. Else False.

    Renders inside Streamlit (caller is responsible for st.stop() after)."""
    page = (page or "").strip().lower()
    fn = _PAGES.get(page)
    if not fn:
        return False
    import streamlit as st
    st.markdown(fn())
    st.divider()
    st.markdown("[← Back to WC26 Picks](/)")
    return True
